"""Agent'in kullanabildiği canonical eylem kümesi."""

from enum import StrEnum


class AgentAction(StrEnum):
    CONTINUE_SCREENING = "CONTINUE_SCREENING"
    RUN_CV_ONLY = "RUN_CV_ONLY"
    RUN_DENSE_ANALYSIS = "RUN_DENSE_ANALYSIS"
    EXPAND_CONTEXT = "EXPAND_CONTEXT"
    RUN_VLM = "RUN_VLM"
    RETRY_VLM_STRICT = "RETRY_VLM_STRICT"
    VALIDATE_EVIDENCE = "VALIDATE_EVIDENCE"
    CONFIRM_EVENT = "CONFIRM_EVENT"
    REJECT_EVENT = "REJECT_EVENT"
    REQUEST_HUMAN_REVIEW = "REQUEST_HUMAN_REVIEW"
    CALCULATE_RISK = "CALCULATE_RISK"
    RETRIEVE_PROCEDURE = "RETRIEVE_PROCEDURE"
    STORE_EVENT = "STORE_EVENT"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    COMPLETE = "COMPLETE"
